local nnoremap = require("thesbx.keymap").nnoremap
local neogit = require('neogit')
local builtin = require("telescope.builtin")

nnoremap("<leader>pv", "<cmd>Ex<CR>")
nnoremap("<leader>pt", "<cmd>Telescope find_files<CR>")
nnoremap("<leader>ps", function()
    builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
nnoremap("<leader>tt", "<cmd>:new +terminal<CR>")
nnoremap("<leader>gs", "<cmd>:Git<CR>")
nnoremap("<leader>gb", "<cmd>:G blame<CR>")
nnoremap("<leader>ga", "<cmd>:Git fetch --all<CR>")
nnoremap("<leader>os", "<cmd>:Neogit<CR>")
nnoremap("<leader>oc", "<cmd>:Neogit commit<CR>")
nnoremap("<C-d>", "<C-d>zz")
nnoremap("<C-u>", "<C-u>zz")
vim.keymap.set("n", "<leader>y", "\"+y")
vim.keymap.set("v", "<leader>y", "\"+y")
vim.keymap.set("n", "<leader>Y", "\"+Y")
vim.keymap.set("n", "Q", "<nop>")
